import { defineConfig } from 'tsup';

// Markdown content is inlined via `src/content-bundle.ts`, generated by
// `scripts/generate-content-bundle.mjs` and run automatically as the
// `prebuild` npm script. This makes help work in both dev and bundled
// CLI builds without copying loose files alongside the dist.
export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: { compilerOptions: { composite: false } },
  sourcemap: true,
  clean: true,
});
