// Re-export relevant types from the official ACP SDK
// All types come from the main entry — the SDK re-exports schema types there.
export type {
  ClientSideConnection,
  SessionUpdate,
  AgentCapabilities,
  ClientCapabilities,
  InitializeResponse,
  SessionNotification,
  AvailableCommand,
  AvailableCommandsUpdate,
  SessionMode,
  SessionModeState,
  CurrentModeUpdate,
  ModelInfo,
  SessionModelState,
  SessionConfigOption,
  ConfigOptionUpdate,
  PlanEntry,
  Plan,
  UsageUpdate,
  Cost,
  Usage,
  ToolCall,
  ToolCallUpdate,
  ToolCallStatus,
  ToolKind,
  SessionInfoUpdate,
  ContentBlock,
  TextContent,
  StopReason,
  PromptResponse,
} from '@agentclientprotocol/sdk';
